version: 0.2

env:
  variables:
    APP_NAME: "was"
  secrets-manager:
    GITHUB_USER: github-bumblebee:githubUser
    ACCESS_TOKEN: github-bumblebee:accessToken
    APP_CONF_REPO: github-bumblebee:appConfRepo

phases:
    install:
      commands:
        - echo "###1. Install kustomize for futher processing ..."
        - |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        - export PATH=$PWD:$PATH
        - kustomize version

    pre_build:
      commands:
        - echo "###1. Logging in to Amazon ECR ..."
        - echo $AWS_DEFAULT_REGION
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

        - echo "###2. Prepare environments for docker image ..."
        - ACCOUNT_ID=$(aws sts get-caller-identity|jq -r '.Account')
        - DOCKER_IMAGE=herochinese/go-bumblebee-$APP_NAME
        - IMAGE_TAG=$CODEBUILD_SOURCE_VERSION
        - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE  
        - |
          export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
          if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
            CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
            export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
          fi
          echo $CODEBUILD_GIT_BRANCH

        - echo "###3. Create an ECR for docker image if need to ..."
        - |
          aws ecr create-repository \
            --repository-name $DOCKER_IMAGE \
            --image-scanning-configuration scanOnPush=true \
            --region $AWS_DEFAULT_REGION || true

        - echo "###4. Retrieve git commit message ..."
        - export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
    build:
      commands:
        - echo Build started on `date`
        - echo "###1. Testing $APP_NAME before build image ..."
        - echo $PWD
        - cd src/$APP_NAME
        - make test

        - echo "###2. Build image for $APP_NAME ..."
        - echo Building $DOCKER_IMAGE:$IMAGE_TAG...
        - docker build . -t $DOCKER_IMAGE:$IMAGE_TAG
        - echo Tagging $REPOSITORY_URI:$IMAGE_TAG...
        - docker tag $DOCKER_IMAGE:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
    post_build:
      commands:
        - echo Build completed on `date`
        - echo "###1. Pushing the Docker image to ECR ..."
        - docker push $REPOSITORY_URI:$IMAGE_TAG

        - echo "###2. Pushing manifests to config repo in GitHub ..."
        - cd $CODEBUILD_SRC_DIR
        - mkdir $CODEBUILD_SRC_DIR/workspace; cd $CODEBUILD_SRC_DIR/workspace 
        - git clone https://$ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
        - git config --global user.email "robot@codebuild.aws"
        - git config --global user.name "robot"

        - cp -r $CODEBUILD_SRC_DIR/manifests/kustomize/$APP_NAME/* $CODEBUILD_SRC_DIR/workspace/$APP_CONF_REPO/kustomize/$APP_NAME/.
        - cp -r $CODEBUILD_SRC_DIR/manifests/kustomize/staging/$APP_NAME/* $CODEBUILD_SRC_DIR/workspace/$APP_CONF_REPO/kustomize/staging/$APP_NAME/.
        - cp -r $CODEBUILD_SRC_DIR/manifests/kustomize/production/$APP_NAME/* $CODEBUILD_SRC_DIR/workspace/$APP_CONF_REPO/kustomize/production/$APP_NAME/.

        - cd $CODEBUILD_SRC_DIR/workspace/$APP_CONF_REPO/kustomize/staging/$APP_NAME
        - kustomize edit set image herochinese/go-bumblebee-$APP_NAME=$REPOSITORY_URI:$IMAGE_TAG
        - cd $CODEBUILD_SRC_DIR/workspace/$APP_CONF_REPO/kustomize/production/$APP_NAME
        - kustomize edit set image herochinese/go-bumblebee-$APP_NAME=$REPOSITORY_URI:$IMAGE_TAG
        - git add -A
        - git commit -m $CODEBUILD_GIT_MESSAGE
        - git push
